// ==UserScript==
// @name        ia solver
// @namespace   ia
// @description Test Solver
// @include     http://*.ugr.es/SCACP/*
// @include file:///*
// @version     1.1
// @grant       none
// ==/UserScript==
//Array de respuestas
var obj = {
		'Losagentesreactivos:.': 'Deben percibir el entorno y responder de una forma temporal a los cambios que ocurren en dicho entorno.',
		'Lainterfazdeusuariodeunsistemaexperto....': 'Es recomendable que se pueda manejar de forma sencilla.',
		'EnelcasodeexistirunacorrespondenciadelosárbolesdejuegoconlosgrafosY/O:.': 'Los nodos O son mis movimientos y los nodos Y los de mi adversario   \nLos nodos O serán los nodos Max y los nodos Y los nodos Min',
		'GrafoY/O.': 'Nodos Y',
		'Lacomplejidaddeunjuegosemide.': 'Con el número de llamadas a la función de evaluación estática',
		'¿Cuáldelassiguientesopcionesresultadedescomponerlasiguientefórmulaaformanormalconjuntiva(FNC):¬(P->Q)v(R->P)?.': '(P v ¬R),(¬Q v ¬R v P)',
		'UsosY/O.': 'Reconocimiento de frases de lengua inglesa   \nResolución de integrales',
		'Respectoalalgoritmodeenfriamientosimulado,escojalasrespuestasverdaderas:.': 'Tiene capacidad para salir de óptimos locales,ya que es un método probabilístico. (34.0 %) \nEs eficiente. (33.0 %) \nEs fácil de implementar. (33.0 %)',
		'Enlafasedebúsquedadelasolución,¿Puedeocurrirqueaunqueseuseungrafoimplícito,sedesbordelamemoria?.': 'Si, puede ocurrir.',
		'Unagentereactivoesaquelquedebepercibirelentornoyresponderdeformatemporalaloscambiosqueocurren,luegoestoimplicaque.': 'Las dos son igual de importantes.',
		'Elaprendizaje…..': 'Modifica el mecanismo de decisión del agente para mejorar su comportamiento.',
		'¿Qúeesunespaciodeestados?.': 'Es la representación del conocimiento que se va generando a través de las acciones del agente.',
		'¿Quediferencialosjuegosdesumanulacontresomasjugadoresdelosjuegosdesumanulaconexactamentedosjugadores?.': 'En los juegos de suma nula con tres o más jugadores pueden aparecer alianzas entre jugadores',
		'EnelalgorítmoA*,g(n)indicaladistanciadelmejorcaminohastaelmomentodesdeelnodoinicialIalnyh(n)expresaladistanciaestimadadesdeelnodoinicialIhastaelnodoobjetivoO..': 'Falso',
		'Seleccionaladefiniciónquemejorseajustealconceptodeespaciodeestados:.': 'Grafo cuyos nodos representan las configuraciones alcanzables (los estados válidos) y cuyos arcos explicitan las acciones posibles.',
		'EnelalgoritmoA*,¿queeslafuncióng?Seleccionalarespuestacorrecta..': 'Es una medida del coste para ir desde el estado inicial hasta el nodo actual',
		'Elempleodeunalgoritmogenéticogarantizasiempreobtenerunasoluciónóptima.': 'verdadero',
		'Marquetodaslasrespuestascorrectas:EnunSMA....': 'No hay un sistema de control global    \nCada agente tiene un punto de vista parcial del problema    \nLos datos no están centralizados    \nLa computación es asíncrona',
		'ladenominadaedadoscuradelaI.A.,fuedebidaaque:.': 'Se necesitaba un gran conocimiento para resolver problemas específicos y la intratabilidad de algunos problemas.',
		'Lossistemasmulti-agentesoninteresantespararepresentarproblemasquetienen:.': 'Múltiples formas de ser resueltos o múltiples perspectivas y/o entidades para resolverlo',
		'Losdosmodelosmásampliamenteusadosenelaprendizajeson:.': 'Divide y vencerás   \nSepara y vencerás',
		'¿QuéenfoquedeInteligenciaArtificialeselqueseusaenagentesreactivos?.': 'Sistemas que actúan racionalmente',
		'Losmétodosheurísticosengeneralnogarantizanlasoluciónóptima,peroproducenresultadossatisfactoriosenlaresolucióndeproblemas..': 'Verdadero',
		'Unrazonamientosellamamonótonocuandoalolargodelprocesoelconjuntode«cosassabidas»essiemprecreciente.¿PorquélamonotoníadelaLógicadepredicadosesunapropiedadindeseableenalgunoscasos?.': 'Porque impide la revisión de las demostraciones a la luz de nuevos axiomas',
		'¿Cuáleseltipodevaloresquepuedentomarlasentradasysalidasdeunárboldedecisión?.': 'Discretos y continuos.',
		'¿Cuálesdelassiguientessoncualidadesposibleosegurasenunagente?NOTA:Cadarespuestainvalidarestaraunaválida.': 'Autonomía: Actuar sin ningún tipo de intervención humana directa, y tener control sobre sus propios actos.   (25.0 %) \nSociabilidad: Comunicarse por medio de un lenguaje común con otros agentes, e incluso con los humanos.   (15.0 %) \nFácil mantenimiento: Al estar distribuidas las funciones y responsabilidades entre varios agentes independientes, es posible reemplazarlos, repararlos y/o actualizarlos.   (-15.0 %) \nCooperación: Con otros agentes para realizar tareas de mayor complejidad.   (15.0 %) \nRacionalidad: el agente siempre realiza «lo correcto» a partir de los datos que percibe del entorno.   (15.0 %) \nCentralización del control: Los accesos a los datos del entorno son controlados por una agente central de forma que cada agente actúa basándose en la información recibida por este.   (-15.0 %) \nAdaptabilidad: Está relacionado con el aprendizaje que un agente es capaz de realizar y si puede cambiar su comportamiento basándose en ese aprendizaje.  (15.0 %) \nNo redundancia: Un agente nunca repite un comportamiento anterior.    (-15.0 %) \nVeracidad: Un agente no comunica información falsa a propósito. (15.0 %)',
		'¿Cuálesdeestascaracteristicaspertenecenaunagentedeliberativo?.': 'Todas las anteriores son correctas',
		'Enunsistemamultiagente(SMA),¿Tienesentidoquetodoslosagentestenganinformacióncompletadetodosuentorno?..': 'falso',
		'Lossistemasexpertossonunejemplode:.': 'Sistemas que actúan como humanos',
		'LaResoluciónesunaregladeinferenciaquegeneralizael"ModusTolens"peronoel"ModusPonens".': 'falso',
		'¿QueesunMC?.': 'Módulo de conocimiento',
		'¿Cuáldelossiguientesalgoritmostieneunmayorrequerimientodememoria?.': 'Búsqueda en anchura.',
		'¿Cuáldelassiguientescaracterísticasdelosagentes,noesindispensable?.': 'Capacidad Social',
		'EnelalgoritmominimaxpodemoscambiareljugadorMAXporeljugadorMINsinmasque:.': 'Cambiar el orden de la exploración y el signo de la función heurística',
		'¿enquebasasusdecisionesunagente?.': 'entorno',
		'¿QuediceelprincipioconocidocomoNavajadeOckham(cuandodosteoríasexplicanloshechosobservados)?:.': 'Que la teoría más simple tiene más probabilidades de ser correcta que la compleja',
		'¿Cuálocualesdelossiguientesalgoritmostienenunacomponentealeatoria?:.': 'Genéticos',
		'LaeficaciadelalgoritmoMINIMAXpararesolverunjuegodadodependeexclusivamentedelaprofundidadqueseempleeparaexplorarelarbol..': 'F',
		'Enelalgoritmodeenfriamientosimulado,¿aquéequivaleuncambiodeestadoenelsistema?.': 'Explorar el entorno de una solución y pasar a una solución vecina.',
		'¿Puedeocurrirqueunnodomintengamayorvalorqueotronodomindescendiente(nodomindemayorprofundidadyconectadoalprimero)?.': 'Si',
		'Elaprendizajeinductivosebasaen....': 'Aprender a partir de ejemplos.',
		'EnelalgoritmoA*ABIERTOSrepresenta.': 'el conjunto de nodos generados y no explorados',
		'¿SenecesitaconocimientoeinformaciónparalaInteligenciaArtificial?.': 'Se necesita de ambos',
		'¿Esposibleunagentesinsensores?.': 'No, porque dejaría de ser un agente al no percibir el entorno en el que se encuentra',
		'Minimax.': '...un método de decisión para minimizar la pérdida máxima esperada en juegos con adversario y con información perfecta',
		'Unaprendizajequesebasaenaprenderapartirdepatronesdeentradassinespecificarsussalidasesunaprendizaje:.': 'No supervisado',
		'Cuáldelassiguientesopcionesnoesuninconvenienteenlafabricacióndelasarquitecturasreactivas:.': 'Simplicidad.',
		'Labúsquedaenanchurapermiteobtenerlasoluciónconmenornúmerodeacciones..': 'verdadero',
		'Losmétodosdeescaladatienencomoobjetivopasarirrevocablementealnodosucesor.': 'que mejore al nodo actual.',
		'Problemadelaaspiradoracondoshabitaciones.': 'verdadero',
		'EnunSistemaMultiagente,laprincipalventajaeslacentralizacióndelosdatos..': 'falso',
		'Lacotabetaes.': 'una cota superior',
		'¿Enquefasedeunagentereactivopercibeelentornodelmundoatravésdesussensores?:.': 'Fase de Percepción.',
		'EspaciodeestadosIII.': 'Un grafo implícito',
		'Laheurísticadadaparaelmapadecarreteras(distanciaenlínearectadesdelaciudadactualaladedestino)permiteobtenerlasoluciónóptimaalproblemasiutilizamosunmétododeescalada.': 'falso',
		'Aaquellosgrafosque,porsureducidotamaño,representanlatotalidaddelproblemaypuedebuscarseuncaminosobreelmismoquenosllevedesdeelestadooriginalhastaelestadoobjetivo,selesdenomina:.': 'Grafos explícitos.',
		'Búsquedaenanchura.': 'Breadth First Search',
		'NavajadeOckham.': 'En elegir la hipótesis más simple consistente con los datos',
		'EnungrafoY/OsitenemosunnodoO,debemos….': 'Resolver un hijo para ver si devuelve la solución, en caso contrario resolver otro hijo y comprobar.',
		'Marcalosenunciadosverdaderossobreunsistemabasadoenpizarra:.': 'Un agente con este sistema se compone de varios módulos.  \nCada módulo se compone de una parte de condición y otra de acción.  \nDos módulos pueden actuar simultáneamente.',
		'UnnavegadorconGPScalculalarutamedianteunagente:.': 'Deliberativo.',
		'Enlabúsquedaenprofundidadretroactiva,elcontenidodelamemoriadetrabajoes.': 'el camino que se está explorando',
		'¿Quéárboldedecisióndesarrollaunahojaparacadaejemplo?:.': 'Trivial',
		'¿Cualocuálesdeestascapacidadessonnecesariasparapasareltestdeturing?.': 'Razonamiento   \nRepresentación del conocimiento',
		'Ruidoenaprendizajees.': 'cuando dos o más ejemplos con la misma descripción de atributos tiene diferentes clasificaciones',
		'ElTestdeTuringtienecomofinalidad:.': 'Demostrar la existencia de inteligencia (artificial) en una máquina',
		'¿Elaprendizajemodiﬁcaelmecanismodedecisióndelagenteparamejorarsucomportamiento?.': 'Sí',
		'SidisponemosdevariasFBFsenunproblema:.': 'Se pueden deducir nuevas FBFs a partir de las que ya tenemos siguiento las reglas de inferencia',
		'Sirealizamosuncambiodeescalaenlosvalores,porejemplomultiplicarelvalorpor10,¿elalgoritmominimaxeligelamismajugada?.': 'si, no depende de los cambios de escala siempre que se conserve el orden',
		'Lamemoriasuponeunamejorade___________enelcomportamientodelagente..': 'precisión y eficiencia',
		'Unárboldedecisión.....': 'toma como entrada un objeto descrito por una serie de atributos y devuelve una decisión que es el valor previsto para la salida con la entrada que se da.',
		'EljuegodeRobocupempleadosmodelosbásicosparamodelarlasituación:entornocooperativoyentornocompetitivo,¿quéagentesformanestosentornos?.': 'Cooperativo: los miembros de un mismo equipo ; Competitivo: los equipos adversarios',
		'Lasinteraccionesentreagentes¿Enquétipodeagentessedan?.': 'Sociales',
		'Enungrafoimplícito,segeneraelgrafoexplícito___________procesodebúsquedadelcaminosolución..': 'durante el,',
		'Labúsquedaretroactivaobacktrackingpertenecea.': 'Búsqueda en profundidad',
		'¿Cuálesdelossiguientesproblemasrequierenparasuresolucióndeunaheuristica?.': 'Una partida de ajedrez  \n8 Puzzle',
		'DelossiguientesejemploscualseriaunproductopropiodeldesarrollodelaIA:.': 'Un navegador GPS',
		'¿Esciertoquetodojuegobipersonalconinformaciónperfectatieneunasolución?.': 'verdadero',
		'Enelproblemadelmonoylosplatano,¿quetipodeagenteseriamaseficaz?.': 'Deliberativo',
		'Cuandosedicequeunagenteescapazderazonarsobreunmodelodelmundoparadecidirquehacerparalograrunobjetivo,estamoshablandodeunagente...........': 'Deliberativo',
		'ElalgoritmoA*siempreterminaynoentraenciclos.': 'tan solo cuando el coste es positivo en cada arco',
		'Unafórmulabienformadadelalógicasesiguelógicamentedeunconjuntodefórmulassi.': 'tiene el valor verdadero bajo todas aquellas interpretaciones para las cuales las fórmulas del conjunto también tienen el valor verdadero',
		'¿Escompletalaresoluciónenelcálculodepredicados?.': 'falso',
		'Losárbolesdedecisiónnopuedentrabajarconvaloresdesalidacontinuos.': 'falso',
		'Cuandotengamosmasdeunahipótesisquesatisfagatodoslosejemplosdebemoselegir.': 'La más simple',
		'DesdeelpuntodevistadelaingenieríacúaldeestasafirmacionesrepresentamejorloquepretendelaInteligenciaArtificial:.': 'Resolver problemas mediante comportamiento racional',
		'Unconjuntodereglasdeinferenciaessólidosi.': 'todo teorema que se puede obtener a partir de un conjunto es una consecuencia lógica de ese conjunto',
		'¿Quérepresentalaadecuaciónconelentornoenunalgoritmogenético?.': 'el valor de la función heurística',
		'AgenteDeliberativo.': 'verdadero',
		'¿Cuálessonlosdosmétodosdeaprendizajesupervisado?.': 'Métodos basados en modelos   \nMétodos basados en instancias',
		'¿Cuáldeestaspropiedadesdeagentesimplicaunfuncionamientomassimple?.': 'Reactivo',
		'Seleccionalasposiblesdefinicionesdeunespaciodeestados:.': 'Grafo cuyos nodos representan las configuraciones alcanzables (los estados válidos) y cuyos arcos explicitan las acciones posibles.  \nEs la representación del conocimiento que se va generando a través de las acciones del agente.',
		'¿ParaquéesnecesarioimplementarunsistemaderesoluciondeconflictosentrelosMódulosdeConocimientodeunSistemaBasadosenPizarras?.': 'Para que determine cúal actuará, si lo harán a la vez, o no lo hará ninguno',
		'Elparadigmadeldilemadelprisioneroindicaque(señalarloINCORRECTO):.': 'La ganancia de un jugador se equilibra con la pérdida de los otros jugadores',
		'¿Enquéconsisteelsobreajusteenelaprendizajeautomático?.': 'En que el algoritmo se centre demasiado en explicar los datos de las muestras y no en generalizar para aprender a resolver el problema.',
		'Laformaenqueelagentepuedeemplearlamemoriaseasemejaríaala___________enloshumanos..': 'memoria a largo plazo   \nmemoria sensorial',
		'Alahoraderepresentarlainformaciónesmásdifícildecidirelquérepresentarqueelcómohacerlo.': 'Cierto.',
		'¿Querepresentacióndegrafos,porsumásreducidotamaño,podríaseralmacenadaenmemoria?.': 'La representación implícita',
		'Eltestdeturinganaliza.': 'Sistemas que actuan como humanos',
		'Cuandoseresuelveunproblemaconunalgoritmogenéticotantolacodificacióndelproblemacomolosoperadoressedebenadaptaralmodelodefinidoporelalgoritmogenético.': 'verdadero',
		'Labúsquedavoraztienecomoobjetivoexpandir....': 'El nodo más cercano al objetivo.',
		'Lacotabetasirve.': 'para podar nodos MAX',
		'¿Quétipodeestrategiasiguelabúsquedaenanchura?.': 'La búsqueda en anchura es una estrategia en la que se expande primero el nodo raíz, a continuación se expanden todos los sucesores del nodo raíz, después sus sucesores',
		'¿Esesencialelusodememoriaenunagentereactivo?.': 'No, pero incluirla provocaría una mejora de la eficiencia y el comportamiento del agente',
		'¿Qúeseconsigueconelaprendizajeautomático?.': 'El perfeccionamiento de la habilidad   \nLa adquisición del conocimiento',
		'Unafuncióndeevaluacióndeunaposiciónoestadoenunjuego.': 'devuelve una estimación de la utilidad esperada de una posición dada',
		'LaLógicadeproposicionesesun"modelodeconocimientoheredable"enelsentidodelasredessemánticas?.': 'falso',
		'Característicasdeunsistemamultiagente.': 'Cada agente tiene una serie de elementos que están conectados entre sí',
		'¿QuétipodeestructuradedatosesrecomendableutilizarparalaimplementacióndelalgoritmodeBúsquedaconCosteuniforme?.': 'cola con prioridad',
		'"Elintercambiodeinformaciónmediantesímbolospuedeproducirfalloslógicos"esunaobjeciónalTestdeTuringdeltipo:.': 'filosófico',
		'Definicióndejuego.': 'Es cualquier situación de decisión, caracterizada por poseer una interdependencia estratégica, gobernada por un conjunto de reglas y con un resultado bien definido',
		'Delassiguientesafirmaciones,¿cuálnoestárelacionadaengeneralconlosAgentesReactivos?.': 'Problemas en trasladar el entorno a una representación simbólica.',
		'Deentrelabúsquedaenanchurayenprofundidad,¿cuáldelosdosusamenosmemoria?.': 'La búsqueda en profundidad',
		'¿Qúeesmáscomplejoeneldiseñodeunagentereactivo?.': 'Percibir correctamente el entorno',
		'Enla___________,losagenteslleganaunacuerdoqueseaaceptableportodaslaspartesimplicadasenlainteracción..': 'negociación',
		'AprendizajeInductivo.': 'Aprender a partir de ejemplos de entradas y sus respectivas salidas',
		'EnunsistemadenavegaciónGPS,¿sepodríarealizarunBacktrackingparaencontrarunaposiblerutahacíaeldestino?.': 'Si, ademas también se podría hacer con un sistema de búsqueda en anchura hasta encontrar nuestro destino.  \nSi, pero no nos asegura encontrar la mejor solución de nuestro problema.',
		'¿Cualdelossiguientesalgoritmosesmáscostosoanivelcomputacional,yporconsiguientemáslento?.': 'Búsqueda en anchura',
		'EnlavalidacióncruzadadeordenN.': 'Se realizan N experimentos, dejando cada vez 1/N de los datos para test y promediando los resultados.',
		'RealizandolapodaALFA-BETAenelmejorcaso..': 'se pueden explorar hasta 2 veces más en profundidad, en la misma cantidad de tiempo',
		'Sepuedenutilizargrafosexplícitos:.': 'En algunos problemas reales con un número reducido de estados.',
		'Enlaresolucióndelcálculodepredicados,alutilizarfuncionesdeSkolemparaeliminarcuantificadoresexistenciales.': 'Se debe utilizar una función distinta para cada uno porque si no se obtiene una  proposición derivada pero no equivalente',
		'¿Queparadigmadeaprendizajeeselqueaprendeapatirdepatronesdeentradaparalosquenoseespecificanlosvaloresdesusalidas?.': 'No supervisado',
		'Enel8-puzzle¿quetipodegrafoutilizarias?.': 'Grafo implicito,',
		'Unproblemadeaprendizajeesrealizable.': 'si el espacio de hipótesis se representa contiene a la función verdadera',
		'Podaalfa-beta.': 'Es una técnica de búsqueda que reduce el número de nodos evaluados en un árbol de juego por el algoritmo Minimax',
		'Enelalgoritmodeenfriamientosimuladolaenergíarepresenta.': 'la función heurística',
		'¿Cuántoscaminossemantendránenmemoriaenlabúsquedaenprofundidadretroactiva?.': '1',
		'EspaciodeestadosII.': 'Representación del conocimiento a partir de las acciones del agente',
		'Losalgoritmosinformados,frentealosdesinformadosoporfuerzabruta,sonaquellosqueposeenunainformaciónextrasobrelaestructuraaobjetodeestudio,lacualexplotanparaalcanzarmásrápidamentesuobjetivofinal,conuncaminodecostomínimodesdeelpuntoinicialalfinal..': 'verdadero',
		'¿Quetipodeagenteutilizaríasparaimplementarunrobotdedicadoalalimpiezadelfondodeunapiscina?.': 'Reactivo, por su bajo coste y fácil implementación.',
		'¿Cuáldeestosproblemasnoesdeinterésparalainteligenciaartificial?.': 'Apagar automáticamente un calefactor cuando haya mas de 30ºC',
		'¿CualdelassiguientesafirmacionessobregrafosY/Oescorrecta?.': 'Para terminar un nodo Y hay que terminar primero todos sus hijos',
		'¿EnquécategoríadeI.A.seencuentraladisciplinadelosmodeloscognitivos?.': 'Sistemas que piensan como humanos',
		'¿CuáldeestaspropiedadesNOesobligatoriaenunagente?.': 'Sociabilidad.',
		'Dadounproblemarepresentablemediantelógicadepredicados,.': 'existen diversas formas de representarlo, no necesariamente equivalentes. Elegir la mas adecuada requiere de una cierta habilidad del diseñador',
		'UnproblemaparaelquehayunaresoluciónalgoritmicanuncapuedeserunproblemadeInteligenciaArtificial.': 'Depende',
		'ElAlgoritmoA*puedeconsiderarseunaextensióndelalgoritmodeDijkstra.': 'verdadero',
		'AgentesReactivos.': 'Subsunción',
		'Unsistemabasadoenelconocimientosolosecomunicaconelusuarioparapedirdatosydarlarespuesta.': 'falso',
		'¿Seríaviablegenerarelgrafocompletopararepresentarelespaciodeestadosdeunajedrez?.': 'No, tendría demasiados nodos',
		'¿QuérespuestaseadecuamejoralarelaciónquetienecualquierpersonaconlaIA:.': 'En la mayoría de las actividades cotidianas con elementos tecnológicos de manera directa o indirecta.',
		'Lautilizacióndelasredesneuronalesparaencapsularagentessebasaensucapacidadde:.': 'Aprendizaje',
		'¿Labúsquedaenprofundidadsedesbordaráantesquelabúsquedaenanchura?.': 'No, tiene menor complejidad en espacio ya que solo mantiene en memoria un camino simultáneamente',
		'¿Porquéesmáscomplejalapercepciónquelaaccióneneldiseñounagentereactivo?.': 'La percepción es más compleja que la acción por que para percibir hay que representar correctamente la situación como un conjunto de características que hay que calcular a partir de los datos de los sensores, mientras que para la acción se implementa un sistema de producción simple que indica como reaccionar según el caso en que se encuentre el agente.',
		'Labúsquedaenprofundidadretroactivaesunaestrategiadelabúsqueda.': 'tentativa',
		'Elaprendizajeesunacapacidadfundamentaldelainteligenciahumana,quenospermite....': 'Desarrollar una gran variedad de habilidades',
		'Delassiguientesopciones,señalelasqueseanciertasparaunagente:.': 'Un agente reactivo, por norma general, será más rápido en dar una respuesta a un estímulo que un agente deliberativo  \nUn agente que toma decisiones en función de los estímulos que recibe y siguiendo un comportamiento programado sin realizar ningún tipo de deducción lógica es un agente reactivo',
		'¿Cualdelassiguientesopcionesseríaesencialimplementarlaenmódulosdeconocimiento(MC)basadoenpizarras?.': 'Un programa de resolución de conflictos cuando dos MCs puedan actuar simultáneamente.',
		'Segúnsufuncionamiento,¿quéestructuradedatosseríamásapropiadaparaimplementarlabúsquedaenprofundidad?.': 'Una pila',
		'¿Unagentequeactúasiempreconindependenciadelentornosiguiendoelmismocriterio,puedeserconsideradounagenteinteligente?.': 'No, porque no tiene flexibilidad y no puede actuar teniendo en cuenta el estado del entorno',
		'¿CúaleslaideaquehaydetrásdeutilizarPROLOGcomoherramientaparaconstruirsistemasbasadosenelconocimiento?.': 'utilizar un formalismo lógico, pero restringuiendo el tipo de conocimiento para que los procesos de inferencia sean eficientes',
		'¿CuandoydondeseconsideraqueseiniciolaInteligenciaArtificialcomodisciplinaocampodeactividad?.': '1956, Conferencia de Dartmouth',
		'LabúsquedaenanchuraesuncasoparticulardelalgoritmoA*.': 'verdadero',
		'LaeficaciadeunalgoritmoMinimaxpararesolverunjuegodependedelaprofundidadconlaquesehagalaexploraciónylacalidaddelaheuristica.': 'V',
		'Actualmente,¿cuálesdeestossoncamposdeaplicacióndelaIA?:.': 'Aplicaciones en e-Salud   \nSistemas empresariales   \nVisión artificial   \nDesarrollo de modelos de inteligencia',
		'Nosiempreesnecesariousarunafuncionheuristicaparaevaluarlosestadosdeunarboldejuego.': 'verdadero',
		'Micromundodelaaspiradora.': 'verdadero',
		'Losagentesreactivosnormalesson.': 'simples y de inteligencia limitada.',
		'Losagentesdeliberativos,encomparaciónconlosagentesreactivos,soncomplejosytardanmásenreaccionaryaquetienenunmodelodelmundo.': 'Verdadero',
		'¿Seusaráobligatoriamenteunagentedeliberativoparajugaraltresenraya?.': 'No necesariamente, porque es un juego simple con un conjunto pequeño de posiciones y se puede conocer la mejor jugada para cada posición',
		'Enrealidadloshombresnosoninteligentes,hacensolamenteloqueledicensusgenes.': 'Falso, los seres humanos aprenden, se adaptan y forman su inteligencia y capacidades a partir de sus herencia genética, pero en función del contexto y las experiencias',
		'Enunjuegoconcomponentealeatorialosvaloresdelosestadosseexpandenhaciaarribacon.': 'la esperanza matematica',
		'Unaspectoatenerencuantaeneldiseñodeunohornoesqueéstedebedeestarenunciertoequilibrio.DelosproblemasenIAdelostrabajosdelavidadiaria,¿cuálcreesqueabordaestetema?.': 'Control',
		'Unhipotéticosistemadetransportedetrenesenelcualpuedehabertantolocomotorasautomatizadascomolocomotorascontroladasporhumanoses....': 'Un sistema multi-agente híbrido con una potente capacidad reactiva',
		'ElModusPonensesunaregladeinferencia.': 'Sólida pero no completa',
		'Laimplementacióndelabúsquedaparcialeneljuegodebehacersecon.': 'Una estrategia retroactiva',
		'ElprocedimientoMinimaxyelprocedimientodepodaalfabetaobtienenexactamenteelmismovalorminimaxparatodoslosnodosdelárbol.': 'verdadero',
		'¿Enquejuegodelossiguientesesnecesariousarunagentedeliberativo?:.': 'El ajedrez   \nEl 8 puzzle',
		'Losproblemasfundamentalesdeunmétododeescaladason.': 'Máximos locales   \nMesetas',
		'ProblemasqueabordalaIA.': 'Análisis financiero',
		'Unabasedeconocimientotansolodebecontemplarconocimientoestáticodelproblema.': 'falso',
		'Elprocedimientodebúsquedaenanchuraactúademanerauniformepornivelesapartirdelnodoinicial..': 'Normalmente se aplica una función denominada función de estados sucesores   \nSe suelen guardar los nodos sucesores en la cola de nodos a explorar',
		'EnlapodaALFA-BETA,betaes….': 'el menor valor en el camino a la raiz desde el nodo, entre los nodos MIN',
		'Lasbasesdeconocimiento....': 'Pueden ser estáticas o dinámicas dependiendo del campo que trate y las necesidades que tiene que cubrir.',
		'¿Dequéformapodemosconocersiunalgoritmopuedepredecirclasificacionesdeejemplosquenohasidoobservados?___________.': 'mediante la validación cruzada   \nmediante el uso de particiones en entrenamiento y test',
		'¿Escorrectalasiguientedefinicióndeagente?:Esunsistemahardwarecapazdepercibirunentornoyactuarenél,secaracterizaporserautónomo,reactivo,pro-activoyracional..': 'verdadero',
		'¿Cuántoscaminossemantendránenlabúsquedaenprofundidadretroactiva?.': '1',
		'¿Cuálesuntipodeaprendizaje?.': 'Aprendizaje Supervisado',
		'Unárboldeljuegoes.': 'una representación explícita de todas las formas de jugar a un juego',
		'EnelalgoritmoA*lafunciónhseinterpretacomo.': 'la estimación del coste del mejor camino entre el nodo actual y un nodo objetivo',
		'¿Quebúsquedaconsumemásmemoria?.': 'Búsqueda en anchura',
		'¿UnprogramadeInteligenciaArtificialdeberesolverunproblemadelamismaformaqueloharíaunserhumano?.': 'No, pero en en muchos casos la forma humana de resolver un problema ayuda a desarrollar la técnica de IA',
		'UnGrafo___________esaquelquerepresentalatotalidaddelgrafodebúsquedadelproblemaypuedeutilizarseparabuscaruncaminosobreelmismoquenosllevedesdeelestadooriginalhastaelestadoobjetivo..': 'Explícito,',
		'Laprincipaldiferenciaentreelalgoritmodeescaladasimpleyelalgoritmodeescaladaporlamáximapendientees.': 'los estados que se tienen en cuenta para la generación del siguiente estado.',
		'Unhijodeunnodominsepuedepodarcuando.': 'alfa es mayor o igual que beta',
		'¿Quéhacediferentealosalgoritmosgenéticosdelosotrosmétodosdeescalada?.': 'el uso de conjuntos de estados y operaciones sobre conjuntos de estados',
		'Cuandounjuegonoesdeinformaciónperfecta.': 'es necesario adaptar los algoritmos para que representen la incertidumbre y/o la falta de información',
		'¿Cuálessonlospasosquellevaacabounagentereactivo?:.': 'Percepción, procesamiento de información, selección de acción en base a la información y realización de la acción.',
		'CualdelassiguientesherramientasNopuedeemplearseparaconstruirunAgenteReactivo.': 'Un Planificador Lógico,',
		'PuedellegaraposeerunreceptordeTDTtécnicasdelaInteligenciaArtificial.': 'Si, por ejemplo para recomendar que ver   \nSi, por ejemplo para procesar la señal de video y mejorar la calidad de imagen',
		'Lacotaalfasirve.': 'para podar nodos MIN',
		'Laefectividaddelapodaalfa-betadelalgoritmominimaxdependedelordenenqueseexplorenlosnodos.': 'verdadero',
		'EnelalgorítmodebúsquedaA*,g(n)expresaladistanciaestimadadesdeelnodonhastaelnodoobjetivoyh(n)indicaladistanciadelmejorcaminohastaelmomentodesdeelnodoinicialaln..': 'falso',
		'¿Quéhaceunprogramaderesolucióndeconflictosenunsistemaconvariosmódulosdeconocimiento?.': 'Evitan que los módulos actúen al mismo tiempo decidiendo el que actúa y el que no.',
		'¿Unagentequejuegaalajedrezesdetipo...?.': 'deliberativo',
		'¿Cualeslautilidaddelamutaciónenunalgoritmogenético?.': 'Para disminuir la probabilidad de quedar atrapado en un óptimo local',
		'Despuésdequeunagentereactivoproceselainformaciónpercibida,debe....': 'Hacer una representación interna de la información percibida.',
		'Labúsquedaenanchuraescompleta,esdecirsiexistesoluciónlaencuentra..': 'verdadero',
		'Laarquitecturadesubsunción…..': 'Consiste en agrupar módulos de comportamiento.',
		'Ademásdecooperaciónynegociacióncualeslainteracciónentreagentesquefalta:.': 'Coordinación',
		'Hoyendía,¿cuáleslaideaclavecuandohablamosengeneraldeInteligenciaArtificial?.': 'Agente inteligente',
		'¿Comoresuelvelosconflictosunagentereactivoconmemoriabasadaenpizarra?:.': 'Añadiendo un módulo de resolución de conflictos.',
		'¿Cuáldelassiguientescaracteristicasnoesindispensableenun"Agente"?.': 'Capacidad Social',
		'¿QuéarquitecturadeAgentescontieneunmodelosimbólicodelmundoexplícitamenterepresentado,ycuyasdecisionesserealizanatravésdeunrazonamientológicobasadoenemparejamientosdepatronesymanipulacionessimbólicas?:.': 'Arquitectura Deliberativa.',
		'Lacotaalfaes.': 'una cota inferior',
		'Búsquedajerárquica.': 'la descripción jerárquica del conocimiento sobre el problema',
		'Elaprendizajebasadoeninstancias.': 'representa el conocimiento mediante los mismos ejemplos',
		'Lossereshumanospodemosconstruiragentesinteligentes,yaqueconocemosysabemosquéeslainteligencia.': 'falso',
		'¿Conquémétododebúsquedaseobtienensiemprelamejorsolución?.': 'Búsqueda en anchura  \nDescenso iterativo',
		'LasreglasdeinferencianospermitenproducirnuevasFBFsapartirdelasqueyaexisten.': 'verdadero',
		'Enunproblemaconcreto,¿queesmásapropiadoutilizaragentesreactivosdeliberativosohíbridos?.': 'Depende del problema, de los requisitos de la solución y del conocimiento de que se disponga',
		'Resolverporvíadelafuerzabrutaelproblemadelviajantedecomercioseríaunabuenaformaparatodosloscasos.': 'Falso, si el tamaño del problema es muy grande consumiría demasiado tiempo',
		'¿Cuálessonlospasosquellevaacabounagentereactivo?.': 'Percepción, procesamiento de información, selección de acción en base a la información y realización de la acción.',
		'¿Cualesdelossiguientesproblemasrequierenparasuresolucióndeunaheuristica?.': 'Una partida de ajedrez  \n8 Puzzle',
		'Enunagentereactivo,¿esnecesarioanticipartodaslasposiblesreaccionesparatodaslassituaciones?.': 'si',
		'EntornoCooperativo.': 'Sí',
		'¿Escompletalaresoluciónenelcálculoproposicional?.': 'verdadero',
		'Elalgoritmominimax.': 'escoge siempre la opción con la que se maximiza el resultado suponiendo que el contrincante intenta minimizarlo   \nevalúa los estados de la frontera de búsqueda con una funcion heurística   \nsuele ser empleado para estrategias óptimas en juegos de suma cero',
		'Unaarquitecturareactivaesaquellaque....': 'no incluye ninguna clase de modelo centralizado de representación simbólica del mundo, y no hace uso de razonamiento complejo',
		'Enlareglaminimax,siJesunnodoMax,entoncessuvalorV(J):.': 'Es igual al máximo de los valores de sus nodos sucesores',
		'FuncionaríacorrectamenteunalgoritmoMinimaxparaeljuegodeltresenrayaqueutilizaralasiguientefunciónheurísticaf(T)=(númerodefilas,columnaodiagonalesaúnlibresparaeljugadorMAX).': 'verdadero',
		'EnelalgoritmoA*CERRADOSrepresenta.': 'el conjunto de nodos generados y explorados',
		'EnelalgoritmoA*elenlacealmejorpadredeterminaunaestructurade.': 'árbol representando los mejores caminos desde cualquier nodo a la raiz',
		'¿QuétipodeagenteseríaunsistemaGPSdeplanificaciónderuta?:.': 'Agente deliberativo.',
		'Elprogramadeenfriamientoconsistede.': 'la temperatura inicial y el cambio de la misma',
		'ElmejorcasodelapodaalfabetapermiteduplicarlaprofundidaddeunprocedimientoMinimaxconlamismacomplejidad.': 'verdadero',
		'Elalgoritmominimax(señalarloINCORRECTO):.': 'La función de evaluación resta en los movimientos propios y suma en los movimientos del contrario',
		'Siunjuegoutilizaunanotaciónmin-max,lafuncióndeevaluaciónestática.': 'Debe contemplar el beneficio para el jugador MAX y el beneficio para el jugador MIN',
		'Aquelquerepresentalatotalidaddelespaciodeestadosdelproblemaypuedeutilizarseparabuscaruncaminosobreelmismoquenosllevedesdeelestadooriginalhastaelestadoobjetivoesungrafo....': 'Explícito.',
		'¿Labúsquedaenprofundidaddesbordarálamemoriaantesquelabúsquedaenanchura?.': 'No, tiene menor complejidad en espacio ya que solo mantiene en memoria un camino en cada momento',
		'¿ComosepuedeintroducirelconocimientoheuristicoenlosSistemasbasadosenReglas?.': 'Ordenando las reglas en la Base de Conocimiento de mayor a menor  interés/importancia/frecuencia.',
		'¿Lapodaalfabetaesnecesariaencualquieralgoritmominimax?.': 'No, la poda alfa beta es una mejora para disminuir el esfuerzo computacional del algoritmo minimax.',
		'Enelcontextodelaprendizajeautomático,¿Quéesunainstancia?.': 'Una observación de una situación conocida en un problema',
		'Unagenteinteligenteesaquelque___________anteunasituacióndada..': 'emprende una acción razonable',
		'¿tendriasentidolautilizacióndeunagenteparalaresoluciondeunlaberinto?.': 'si, porque habría que actuar en función del entorno',
		'Cuandolasalidadeunárboldedecisionesesunavariablecontinua,elproblemasedenomina.': 'regresión',
		'DefinicióndeIA.': 'Disciplina científico-técnica que se ocupa de la comprensión de los mecanismos subyacentes en el pensamiento y la conducta inteligente y su incorporación en las máquinas',
		'¿Puedeexistirunjuegocompetitivoycooperativoalavez?.': 'Sí, por ejemplo la Robocup en la cual una parte es cooperativa (entre los agentes de un equipo) y otra competitiva (contra el otro equipo).',
		'Unrobotprogramadoparajugaralasdamas,normalmentehaceusodeun:.': 'Agente deliberativo',
		'Segúnaumentalahomogeneidad(enelsentidodeserlamayoríadelosejemplosdecadahojadelamismaclase):.': 'aumenta la ganancia de información.',
		'Latécnicabracktrakingesunmétododebúsquedadesoluciones:.': 'Exhaustiva sobre grafos dirigidos acíclicos',
		'¿Estodoconocimientorepresentablemediantelógicadepredicados?.': 'falso',
		'Búsqueda.': 'Retroactiva',
		'Todoslossistemasbasadosenconocimientotieneunmódulodejustificación:.': 'No pero se puede implementar según el problema y las necesidades del cliente/experto que lo va a usar.',
		'EmpleandotécnicasdeInteligenciaArtificialpodemosconstruir:.': 'Sistemas que actúan racionalmente,  \nSistemas que actúan como humanos,',
		'¿Quédosdelassiguientescaracterísticastienenlasrepresentacionesdescriptivasquelashacenmásventajosasquelasrepresentacionesicónicas?:.': 'Son fáciles de comunicar a otros agentes.   \nSe pueden descomponer en piezas más simples.',
		'LaResoluciónesunaregladeinferenciaquegeneralizael"ModusPonens"peronoel"ModusTolens".': 'falso',
		'ElprocedimientoMinimaxyelprocedimientodepodaalfabetaobtienenexactamenteelmismovalorminimaxdelnododeinicioylamismajugadaminimax.': 'verdadero',
		'La______funcionaimpidiendodivisionesrecursivassobreatributosnorelevantes..': 'Poda de arboles de decision.',
		'¿Enquéconsisteenproblemadesobreajuste?.': 'Hace que un sistema aprenda incluso los errores sistemáticos o aleatorios de los datos con los que trabaja, lo que provoca que luego su rendimiento en interpolación o generalización sea muy ineficiente.',
		'Losdosalgoritmosmásampliamenteusadosenelaprendizajeson:.': 'Divide y vencerás   \nSepara y vencerás',
		'Respectoalproblemadelviajantedecomercio..': 'Aplicar una heurística optimizaría la búsqueda de una solución',
		'¿Cuáleselprincipalproblemaatenerencuentaalrealizareldiseñodeunagentedeliberativo?.': 'La complejidad de la búsqueda del estado o estados objetivo',
		'¿Quérepresentaciónesmásrecomendablesiquiererepresentarseinformaciónincierta?.': 'Representaciones descriptivas',
		'EncomparacióndelosGrafosImplícitoseExplícitos:.': 'Los explícitos son más eficaces pero en la practica no siempre se pueden aplicar por desbordamiento de memoria.',
		'Enaprendizajeunahipótesisestarábiengeneralizadasi.': 'puede predecir ejemplos que no se conocen',
		'ElprincipalproblemadelalgoritmoA*eslamemoria..': 'verdadero',
		'Ordenelospasosdelalgoritmodeescaladaporlamáximapendiente..': '1  ->  Evaluar el estado inicial. Si también es el estado objetivo, devolverlo y terminar. En caso contrario, continuar con el estado inicial como estado actual. \n2  ->  Partir de la solución actual. Expandirla. \n2.1  ->  Buscamos de todos los “nodos pendientes” el de mejor calidad. \n2.2  ->  Si es “mejor” que la solución actual entonces se sustituye la solución actual por dicho nodo. Volvemos al paso 2 \n2.3  ->  si no parar.  \nPuntuación: 0.2',
		'Definicióndeagenteinteligente.': 'Es un sistema de ordenador, situado en algún entorno, que es capaz de realizar acciones de forma autónoma y que es flexible para lograr los objetivos planteados',
		'LacalidaddelarespuestadelalgoritmoMINIMAXdependeexclusivamentedelaprofundidadqueseempleeparaexplorarelarbol..': 'F',
		'Enunjuegoconcomponentealeatoria,sirealizamosuncambiodeescalaenlosvaloresmedianteunafunciónrealcreciente(escalalineal,escalalogarítmicas,etc..),¿lavariantedelminimaxparaestetipodejuegoselegirálamismajugada?.': 'No siempre, pero si el cambio de escala consiste en multiplicar por un número positivo si,    \nNo siempre, pues puede cambiar el orden de la esperanza matemática de las opciones de una jugada aunque se conserve el orden de los valores',
		'¿Cualdelassiguientesafirmacionespertenecealnivelheurísticodelconocimiento?.': 'las averías electricas son más fulminantes que las averías mecanicas',
		'LosrobotsautonomosdeexploraciondeMartenosonreactivosporque....': 'tienen un modelo simbolico del mundo   \ndeciden su comportamiento de la forma que mejor satisfaga sus objetivos',
		'¿Quécorrespondealareproducciónsexualenunalgoritmogenético?.': 'el operador de cruce',
		'Elalgoritmominimaxes.....': 'un método de decisión para minimizar la pérdida máxima esperada en juegos con adversario y con información perfecta',
		'Elagentereactivopercibesuentornoatravésde.....': 'Sensores',
		'Todojuegobipersonalconinformaciónperfectatienesolución.': 'La afirmación es cierta pero no podemos conseguir resolver de forma práctica juegos complejos',
		'SiAesunconjuntodefbfs,ybesunafbfquenoestáenA¿PuedenexistirdosmodelosdistintosquesatisfagantodaslasfbfdeA,detalformaqueunosatisfagabyelotronosatisfagab?.': 'verdadero',
		'BúsquedaenprofundidadII.': 'Solo si el grafo es finito y no se pone límite a la profundidad de exploración',
		'Unagentereactivobasadoenmodelosiconicos___________aunagentereactivobasadoencaracterísticas..': 'es una alternativa que incluye memoria',
		'¿CualdelassiguientescaracterísticasNOesimprescindibleenunagente?.': 'Social',
		'¿Seríaviableenunrobotaspiradorusarunaimplementacióndelamemoriaconrepresentacionesicónicas?.': 'Si, porque es una buena manera de representar lo que ha percibido y poder tomar decisiones basadas en ello',
		'¿Cuálocuálesdelasiguientescaracterísticassondeunagentedeliberativo?:.': 'Elementos centralizados   \nRazonamiento lógico',
		'¿Quéesunademostración?.': 'Una secuencia de FBFs se llama demostración o deducción de w a partir de ∆ si, y sólo si, cada valor de la secuencia pertenece a ∆ o puede inferirse a partir de FBFs en ∆ mediante un conjunto de reglas de inferencia',
		'Decimosqueunsistemaderazonamientológicoesdecidiblesilainferenciaes.': 'factible',
		'Unejemplodeagente___________seríaunoquejuegaaltresenraya..': 'ambas',
		'Cualdelassiguientescaracterísticasnopertenecealdiseñodeunagentereactivo:.': 'El agente tiene conocimiento de si mismo y de su entorno.',
		'Unincovenientedelosmétodosdeescaladaesquenoesfácilresolverproblemasquerequierenencontraruncamino(secuenciadeacciones)conellos.': 'verdadero',
		'¿Aquenosreferimoscuandohablamosde"granularidad"delarepresentacióndeunciertoconocimiento?.': 'Al nivel de detalle con que se reflejan los hechos o relaciones',
		'¿Cuálocuálesdelassiguientesafirmacionesacercadelosalgoritmosdebúsquedanoinformadasonciertas?.': 'La búsqueda en anchura garantiza obtener la solución óptima siempre y cuando el coste de los operadores sea constante.',
		'Elalgoritmodeenfriamientosimuladoesunavariantedelosmétodosdeescaladaquesecaracterizaporpoderseleccionarenalgunoscasosestadospeoresqueelactual..': 'Verdadero',
		'Señalacualdelassiguientesetapaspertenecealciclodepercepciónyaccióndeunagentereactivo.NOTA:SiAlgunadelasrespuestaseserrónealapreguntaseconsiderarámal..': 'Procesamiento de las entradas percibidas por los sensores   (25.0 %) \nProcesamiento de las entradas percibidas los actuadores   (-100.0 %) \nEscoger una acción, entre las posibles, considerando la información percibida   (25.0 %) \nDecide que acción realizar con la información de experiencias pasadas   (-100.0 %) \nProcesamiento de las salidas que se enviaran a los actuadores   (25.0 %) \nHacer una representación interna perceptual de las información percibida   (25.0 %) \nAgrupar los módulos de comportamiento teniendo en cuenta la información percibida  (-100.0 %)',
		'LosMC(módulosdeconocimiento)almacenan…..': 'Ambas.',
		'Hipótesis.': 'Cuando pueda predecir ejemplos que no se conocen',
		'AgenteDeliberativos.': 'Un modelo de los efectos de sus acciones en el mundo',
		'Unarepresentaciónicónicapermitedefinirleyesgenerales.': 'falso',
		'¿Cualdeestastécnicascreesmasadecuadaparaunsistemadeplanificaciónderuta?:.': 'Búsqueda con costo',
		'¿QuérepresentanlosnodoscuandoseusalaestructuradegrafodirigidopararepresentarunproblemaenInteligenciaArtificial?¿Ylosarcos?.': 'Nodos: un estado del sistema ; Arcos: una posible acción',
		'Unagentereactivo....': 'una vez que toma una decisión, no la puede cambiar  \nescoge una acción, entre las posibles, considerando la información recibida   \núnicamente se basa en lo que percibe del mundo para tomar su decisión',
		'Cuandolasalidadeunárboldedecisiónescontinuaelproblemasedenomina.': 'regresión',
		'Lasredesneuronalesalmacenanlainformacióndeformaredundante:.': 'No, no tiene por qué',
		'Unrobotdiseñadoparajugaralfutbol.': 'Necesita de ambos agentes',
		'Elalgoritmoalfa-betacalculaelmismomovimientoqueelalgoritmominimaxperoconmayoreficiencia.': 'V',
		'¿Unagentequeseapro-activodebesercapazdeexhibircomportamientosdirigidosalograrlosobjetivosqueseplantee?.': 'V,',
		'Enelalgoritmodeenfriamientosimuladolatemperaturarepresenta.': 'un paramétro artificial que permite controlar la conducta del algoritmo a lo largo del tiempo',
		'Cualdeentrelossiguientesalgoritmosdeescaladaevitalacaídaenóptimoslocales..': 'enfriamiento simulado',
		'Unagenteesunsistemaque___________..': 'actúa racionalmente',
		'¿Cúaldelossiguientesproblemasnodebieramodelizarsecomounagentereactivo?.': 'Navegador GPS   \nCoche autonomo',
		'¿Conquémétododebúsquedaseobtienensiemprelasoluciónconunnúmeromenordepasos?.': 'Búsqueda en anchura  \nDescenso iterativo',
		'¿Porquéhoyendíaestanimportanteelcampodeaplicacióndelossistemasdeaprendizajeautomático?.': 'Porque en muchos casos se dispone de una gran abundancia de datos sobre el problema.',
		'ParapoderdecirqueunaFBFesunteorema¿esnecesariodisponerdeunconjuntodereglasdeinferencia?.': 'verdadero',
		'Espaciodeestados.': 'Proyectando el problema de las distintas opciones',
		'Búsquedaenprofundidad.': 'DFS',
		'¿Cuálessonlosproblemasdelaformatrivialdeinferirunárbol?.': 'Se crean arboles demasiado grandes.    \nSe pierde la referencia al nodo padre.   (-25.0 %) \nNo funciona bien con nuevas instancias.    \nInviable computacionalmente. (-25.0 %)',
		'¿Cuálocuálesdelassiguientesafirmacionesacercadelosalgoritmosdebúsquedanoinformadasonciertassielcostedelosoperadorespuedesercualquiernúmeroenteropositivo?.': 'Si existe una solución, la búsqueda en anchura la encuentra.  \nSi la variante con costo de la búsqueda en anchura encuentra una solución, ésta debe ser óptima.  \nPuntuación: 0.5',
		'¿CuálocualessonloscomponentesbásicosquenecesitaunSistemaBasadoenelConocimiento(SBC)?.': 'Base de Conocimiento (BC)  (33.0 %) \nMotor de inferencia  (33.0 %) \nInterfaz de usuario  (34.0 %)',
		'Labúsquedaenprofundidadconsisteeniranalizandodesdeelestadoinicialelsucesordelnodoactualdemenornivelgeneradohastaelmomento..': 'Falso',
		'Enrealidadloscomputadoresnosoninteligentes,hacensolamenteloqueledicenlosprogramadores.': 'Verdadero, pero se pueden comportar,actuar o responder \'de forma inteligente\'',
		'Lacaracterísticacapacidadestímulo-respuestadeunagentesedefinecomo:.': 'El agente debe percibir el entorno y responder de una forma temporal a los cambios que ocurren en dicho entorno.',
		'ParaelfuncionamientodeunGPS,estedebedisponer:.': 'Ambas anteriores.',
		'Enlabúsquedadeanchuraesnecesarioiranalizandodesdeelestadoinicialtodoslossucesoresdecadanodoantesdepasaralnivelsiguienteenelárboldebúsqueda..': 'Verdadero',
		'Laheurísticadadaparaelmapadecarreteras(distanciaenlínearectadesdelaciudadactualaladedestino)¿esadmisible?.': 'verdadero',
		'¿Cuálocualesdelossiguientesjuegossondeterminísticosyconinformacióncompleta?:.': 'Ajedrez   \nDamas',
		'Ungrafoexplicito:.': 'Representa la totalidad del problema.',
		'Elsubsistemadeexplicacióndeunsistemaexpertobasadoenreglastienecomomisión.': 'justificar como se ha llegado a la decisión propuesta por el sistema',
		'Enlazacadavariantedelmétododeescaladaconsudefinición:.': 'Escalada de primera opción  ->  Se generan aleatoriamente sucesores, escogiendo el primero con mejor valoración que el estado actual \nEscalada con reinicio aleatorio  ->  si no te sale a la primera, inténtalo otra vez \nEscalada estocástica  ->  Escoge aleatoriamente entre los sucesores con mejor valoración que el estado actual.',
		'Lacotaalfasecálcula.': 'máximo de los nodos MAX entre el nodo y la raiz',
		'Lacotabetasecálcula.': 'mínimo de los nodos MIN entre el nodo y la raiz',
		'¿Comopodríabeneficiarelusodeunaarquitecturadesubsunciónenunrobotaspirador?.': 'Los estímulos del exterior se procesan por capas especializadas de modo que se siguen unas prioridades a la hora de actuar   \nPermitiría modularizar el comportamiento y facilitar la implementación',
		'¿ParaquésedebeimplementarunprogramaderesolucióndeconflictosenunMCbasadoenpizarras?.': 'Para impedir que dos módulos puedan acceder simultáneamente a la pizarra.',
		'ElperiododegestacióndelaIAfue___________..': '(1943-1955)',
		'LaNavajadeOckhamesunprincipioquediceque.': 'ante dos soluciones que expliquen un problema es preferible la solucion mas simple.   \nla solucion mas simple a un problema es posiblemente la correcta porque si fuera algo mas complejo se tendria el conocimiento que indicaria que esa complejidad debe formar parte de la solucion.',
		'Unagenteesautónomocuandoseapoyamásenelconocimientoinicialqueleproporcionaunhumanoqueensuspropiaspercepciones..': 'verdadero',
		'Elprincipalproblemadelosalgoritmosgenéticoseseldeencontrarseconunmáximolocal..': 'falso',
		'ElalgoritmodeDijkstraseobtienecuandoenelalgoritmoA*setoma.': 'h es igual a cero',
		'EnelalgoritmoA*cuandounsucesorcorrespondeconunnodoqueyaestabaenCERRADOS.': 'el nodo se revisa para determinar cual es su mejor padre, y en el caso de que haya cambio se propaga dicho cambio a los sucesores.',
		'GrafosY/O.': 'Para completar el objetivo A, es necesario terminar antes los objetivos B y C.',
		'Elalgoritmominimaxsepuedeemplearen:.': 'juegos de suma nula con 2 jugadores e información perfecta',
		'Pararesolverelproblemadeespacioenelárboldelminimaxsepodría(señalarlarespuestaINCORRECTA):.': 'Aplicar una búsqueda en profundidad para llegar antes al movimiento final',
		'¿CuáldeestasáreasdedesarrollosehamencionadoenclaseespecíficamentecomoimportantesparaeldesarrollodelaI.A?.': 'Economía',
		'Elprincipalproblemadelaprendizajeautomáticoes.': 'Sobreajuste',
		'¿Cuáldelossiguientesalgoritmosencuentraelóptimoconunaheurísticaadmisible?:.': 'A*',
		'¿Comosellamalatécnicaqueconsisteendemostrarquelanegacióndeunacláusulaesinconsistenteconlosaxiomasdelsistemaparaconseguirquesequedeasíprobada,portanto,laveracidaddedichacláusula?:.': 'Refutación',
		'Paralaimplementacióndeunmodeloicónicosepuedenusar:.': 'Cualquier estructura de datos',
		'LaHabitaciónChina.': 'verdadero',
		'Labúsquedaenprofundidadconsisteeniranalizandodesdeelestadoinicialunsucesordelnododemenornivelgeneradohastaelmomento..': 'Falso',
		'Enlossistemasdeaprendizajeautomáticosebusca.': 'aprender a conocer y/o resolver el problema basandose en los ejemplos.',
		'Unalgoritmodeaprendizajeesbuenosi….': 'Produce hipótesis que hacen un buen trabajo al predecir clasificaciones de ejemplos que no han sido observados.',
		'¿QuésonlascláusulasdeHorn?:.': 'Aquellas que tienen a lo sumo un literal positivo',
		'¿Quétipodeagenteconllevaunamayorcomplejidad?.': 'Deliberativo',
		'Elusodeprobabilidadesenalgunosmétodosdeescaladasejustificapor.': 'incrementar la capacidad de exploración del algoritmo',
		'¿Unmétododeaprendizajebasadoeninstanciasrepresentaelconocimientomedianteejemplosdelconjuntodeentrenamiento?.': 'verdadero',
		'Unagentereactivo,¿conocenecesariamentetodosuentorno?.': 'no',
		'Unespaciodeestadoseslarepresentacióndel___________quesevagenerandoatravésdelasecuenciadeaccionesdelagente..': 'conocimiento',
		'Losprincipalesproblemasdelosagentesreactivosson:.': 'Necesitan disponer de suficiente información sobre su entorno para actuar adecuadamente,  \nNo hay metodologías claras para crear este tipo de agentes: sigo siendo un desarrollo por prueba y error.,  \nEs difícil el aprendizaje y la mejora de las capacidades de los agentes con el tiempo.,',
		'Unaventajadelosmétodosdeescaladaesquesonsiemprefácilesdeimplementar.': 'verdadero',
		'EnLógicadePredicadosdoscuantificadorespuedencambiardeordenenunafbfsinalterarlasemánticadeesta.': 'No solo cuando los dos cuantificadores sean del mismo tipo, existencial o universal.',
		'Algunasdelascaracteristicasprincipalesdelosarbolesdedecisionson.': 'su gran expresividad.   \nsu uso como herramientas de desarrollo,',
		'¿Paraquéseutilizalavalidacióncruzada?.': 'Para asegurar más homogeneidad.',
		'¿CuáldelossiguientesmétodosdebúsquedaesuncasodeMejor-Primero?.': 'A*',
		'Enunagentereactivobasadoenunmodeloicónico,lamemoria.': 'Es la conjunción de ambas cosas',
		'Sistemamultiagente.': 'Los entornos en los que dos o más agentes intervienen simultáneamente',
		'Unagente___________actúaencualquiersituaciónmedianteunprocesoestímulo/respuestaanteelestadoactualdelentornoenelcualestásituado..': 'reactivo',
		'Unejemplodeagentedeliberativoseria....': 'Agente para resolver el Problema del mono y los plátanos.  \nSistema GPS.',
		'ElalgoritmoID3:.': 'tiende a elegir atributos con muchos valores posibles.',
		'Espreferibleordenarlosestadosdemenoramayorenlosnodosmaxantesquedemayoramenorenlosnodosmin.': 'verdadero',
		'Unagenteproactivoalpercibirunentorno:.': 'tiene comportamientos que le permite lograr objetivos usando el conocimiento del mundo',
		'Eligedelassiguientesrespuestasaquellasquesonverdaderas.': 'Para el juego del Ajedrez se utiliza heurística.  \nEn algoritmos de enfriamiento simulado,un modo de evitar que la búsqueda local finalice en óptimos locales, es permitir que algunos movimientos sean hacia soluciones peores.  \nEn el algoritmo A*, h(n) expresa la distancia estimada desde el nodo n hasta el nodo objetivo O.',
		'RealizandolapodaALFA-BETA…..': 'se pueden explorar hasta 2 veces más en profundidad, en la misma cantidad de tiempo',
		'¿QuéinconvenienteoinconvenientestienerepresentarunproblemaconcláusulasdeHorn?:.': 'La representación del problema podría ser más difícil',
		'¿Cuálocuálesdelossiguienteselementossonlosmásadecuadospararepresentarlasituaciónenlaquenosencontramosjugandoal"tresenraya"?.': 'Matriz 3x3   \nVariable turno',
		'¿Cualessonlasfasesdeprocesoenunagentereactivo?:.': 'Procesamiento perceptual y Fase de calculo de la acción.',
		'Enlossistemasdeaprendizajeautomaticosebusca.': 'aprender a resolver el problema basandose en los ejemplos   \nconocer en que momento se debe parar para evitar el sobreaprendizaje',
		'Puedeserunaposiblecausadelruidolanoexistenciadeunnúmerosuficientedevariablesrelevantesdelproblema___________.': 'verdadero',
		'¿Cúalesdelossiguientesalgoritmoshacenusodedecisionesestocásticas?.': 'Enfriamiento Simulado   \nAlgoritmo de escalada de primera opción',
		'¿Comoeseldiseñodeunagentereactivo?:.': 'Percibe, Procesa las entradas, Representa lo percibido, Selecciona una acción, Procesa la salida y actúa.',
		'Losalgoritmogenéticossonmétodosdeescaladabasadosen.': 'la evolución natural',
		'Unahipotesisesconsistentesi.': 'satisface a los datos',
		'EnInteligenciaArtificiallosÁrbolesdeDecisiónsonunatécnicaencuadradadentrodelAprendizajeAutomático.¿Sabríadeciraquésededicaestecampo?.': 'estudia los procesos o técnicas que permiten al software "aprender" o adquirir conocimientos que le permitan resolver problemas en un futuro, o bien adaptarse a partir de la experiencia.',
		'Cuálesdelassiguientesopcionessoncorrectas.': 'El agente deliberativo dispone de un modelo del mundo en el que habita.    \nEl agente deliberativo dispone de un modelo de los efectos de sus acciones sobre el mundo.   \nEl agente deliberativo reacciona a los cambios que percibe auque no estén en su modelo del mundo. (-50.0 %)',
		'Cuáldelassiguientesopcionesnoescorrectaconrespectoalmundodelosbloques:.': 'En esta estructura, un arco representa un estado del sistema y un nodo una posible acción.',
		'¿CuálocuálesdelassiguientecaracterísticassonpropiasdeproblemasdeIA?.': 'No tienen una solución exacta que sea eficiente   \nDifíciles',
		'Unalgoritmogenéticosiempreencuentraelóptimodelafunciónsobrelaqueseaplica..': 'F',
		'UnAgenteesunsistemadeordenador,situadoenalgúnentorno,que....': 'es capaz de realizar acciones de forma autónoma y que es flexible para lograr los objetivos planteados',
		'¿Cuáleslaprincipaldificultadaldiseñarunagentereactivo?___________.': 'Encontrar la lógica para calcular la acción   \nEl proceso del cálculo de la situación a partir de los datos de los sensores',
		'¿Sepuededarsemánticaaunafbfquecontengavariableslibres?.': 'No, en ningún caso',
		'EnelalgoritmoA*lafunciónhesunvalorquenocambiaalolargodelalgoritmo.': 'verdadero',
		'¿Puedencombinarselosgrafosexplícitosylosimplícitosensistemasdebúsquedadeagentesdeliberativos?.': 'Si y deben hacerlo para resolver un problema.',
		'Elalgoritmodeescaladaestocáticoseleccionaelsiguienteestado.': 'aleatoriamente entre todos los descendientes que mejoran al actual y con una probabilidad para cada descendiente proporcional al valor de la heurística en el mismo',
		'¿Quéestrategiadecontrolutilizaunmétododeescalada?.': 'Irrevocable',
		'Cuantomayorseanuestronúmerodeejemplosparaunárboldedecisión....': 'más se asemejará a la realidad.',
		'¿Queesunaheurística?___________.': 'Un criterio para determinar lo prometedora que es una alternativa en relación con un determinado objetivo.',
		'¿Quéfuellamadooriginalmente"eljuegodelaimitación"porsucreador?.': 'El test de Turing',
		'¿Cuálocualesdelossiguientesjuegossonbipersonalesconinformaciónperfecta?:.': 'Ajedrez   \nDamas',
		'Elprocedimientoderefutaciónmedianteresoluciónconsisteen“aplicarresolucioneshastaquesegenerelacláusulavacíaonosepuedanhacermásresoluciones”.': 'verdadero',
		'¿Cuálesdelossiguientesmétodossonbúsquedasininformación?.': 'búsqueda en anchura, búsqueda en profundidad',
		'Lasleyesdelpensamientoseasocianconlos:.': 'Sistemas que piensan racionalmente',
		'Relacione:.': 'A. genéticos  ->  Son métodos para la resolución de problemas de búsqueda y optimización  \nA*  ->  Se emplea para resolver problemas como el camino más corto. \nR. neuronales  ->  Son modelos de aprendizaje y aproximación.',
		'Paraasegurarseelencontrarunasoluciónalproblema,¿Quéseríamejorutilizarunaestrategiadebúsquedaenanchuraobúsquedaenprofundidad?.': 'Búsqueda en anchura',
		'Entrelasmúltiplesformasdeinferirunárboldedecisiónlamásusadayeficazconsisteen:.': 'Seleccionar el atributo en cada nivel del árbol en función de la calidad de la división que produce.',
		'Enelejemplodelrobotaspiradorsepodríausar....': 'una arquitectura de subsunción   \nuna memoria con representaciones icónicas',
		'Laheurísticadadaparaelmapadecarreteras(distanciaenlínearectadesdelaciudadactualaladedestino)permiteobtenerlasoluciónóptimaalproblemasiutilizamoselalgoritmoA*.': 'verdadero',
		'Cuáldelassiguientesopcionesnoesunaventajaenlasarquitecturasreactivas:.': 'Los sistemas reactivos pueden ser utilizados para varios propósitos.',
		'Elcasopromediolapodaalfabetapermiteprofundizar.': 'un 33% más que un procedimiento Minimax con el mismo esfuerzo',
		'LaInteligenciaArtificialsebasaen:.': 'Conocimiento + Razonamiento',
		'Unagentereactivo:.': 'No mantienen historia pasada ni estado',
		'¿Eseficientelaresoluciónenlógicadepredicados?.': 'Si, siempre que nos limitemos a utilizar clausulas de Horn',
		'¿Elusodeunafunciónheurísticagarantizaqueunmétododebúsquedaconsigalasoluciónóptima?.': 'Depende del algoritmo y de la heurística',
		'DesdeelpuntodevistadelaRepresentacióndelConocimientohaygrandiferenciaentrelaspropiedadesdeunconjuntodeobjetosylaspropiedadesdelosobjetosdeeseconjunto.': 'Si, un conjunto como tal tiene propiedades muy diferentes de las propiedades de los objetos que forman parte de él.',
		'Laincertidumbreproducidaporlatiradadeundadosemide.': 'con el caso promedio',
		'CaracterísticasdeunSistemaMulti-Agente:.': 'No hay un sistema de control  global.   \nLos datos no están centralizados.   \nCada agente tiene información incompleta, o no todas las capacidades para resolver el problema, así cada agente tiene un punto de vista limitado.',
		'Elprocedimientodebúsquedaenanchuraactúademanerauniformepornivelesapartirdelnodoinicialy.': 'se suelen guardar los nodos sucesores en la cola de nodos a explorar.',
		'Sedicequeunproblemadeaprendizajeesrealizablesielespaciodehipótesis.': 'contiene a la función verdadera',
		'¿Quétipodeaprendizajeaprendeunafuncionapartirdeejemplosdesusentradasysalidas..': 'Aprendizaje supervisado',
		'Relacionelossiguientesconceptos..': 'Búsqueda en anchura  ->  Recorre todos los sucesores de cada nodo antes de bajar de nivel \nBúsqueda con Costo  ->  Expande el nodo cuyo camino es más barato \nBúsqueda en profundidad  ->  Expande todos los nodos que va localizando, de forma recurrente, en  un camino concreto.',
		'Larefutaciónmedianteresoluciónenlógicadepredicadoses.': 'sólida y completa',
		'LaEvoluciónHistoriadelaIA:.': 'Ha tenido altibajos, pero en los últimos está teniendo un desarrollo progresivo y rápido',
		'¿Paraunapartidadeajedrez,porejemplo,cuáleselagentemasidóneopararealizarla?.': 'Deliberativo',
		'Losagentesinteractúanconlosambientesatravésdesensoresyefectores.': 'verdadero',
		'EnlapodaALFA-BETA,βes…..': 'el valor de la mejor opción hasta el momento a lo largo del camino para MIN',
		'Losalgoritmosbasadosenel“divideyvencerás”(splitting),consistenenencontrarcondicionesdelasreglasquecubranlamayorcantidaddeejemplosdeunaclaseylamenorenelrestodelaclase..': 'Falso',
		'Laarquitecturadepercepción/planificación/actuaciónpermitequeunagentepuedaresolverproblemasenunentornodinámico.': 'verdadero',
		'SedicequeunaFBFesválidasi.': 'se cumple independientemente de la interpretación que se le asocie',
		'AplicacionesdelaIA.': 'Robótica',
		'Unagente___________tienelainciativayescapazdeaprovecharoportunidades..': 'Deliberativo',
		'¿Sonlosrobotsqueparticipanenlarobocupagentesreactivos,deliberativosohíbridos?.': 'Reactivo    \nHíbridos',
		'Señalarcualesdeentrelossiguientessonmodelosderazonamiento:.': 'Lógica de predicados   \nLógica de proposiciones',
		'Enunjuegoconcomponentealeatorialosvaloresdelosestadossepropaguenhaciaarribacon.': 'la esperanza matematica',
		'EnelalgoritmoMINIMAXsepartedelahipótesisdequelosdosjugadoresjuegandemaneraperfecta.¿Queocurresiunodeellosfallaynoactúasegúnloprevisto?.': 'El contrincante se beneficia',
		'ProfundidadvsAnchura.': 'Siempre encuentra el camino mas corto',
		'¿Elaprendizajeporrefuerzoesunaprendizajesupervisado?.': 'falso',
		'LacalidaddelarespuestadadaporunalgoritmoMinimaxdependedelaprofundidadconlaquesehagalaexploraciónylacalidaddelaheuristica.': 'V',
		'Lasreglasobtenidasapartirdeunárboldedecisiónnosonexcluyentes..': 'falso',
		'LaBúsquedaprimeroelmejoroporelmejornodohaceusodeunaestrategiadecontrol.': 'Exploración en grafos',
		'¿Puedetenermemoriaunagentereactivo?.': 'verdadero',
		'Elalgoritmominimaxdependedelordenenqueseexplorenlasjugadas.': 'verdadero',
		'ElvalorV(J)deunnodoJdelafronteradebúsquedaes___________aldesuevaluaciónestática..': 'igual',
		'Haytrestiposdeagentes:agentessociales,agentesreactivosy....': 'Deliberativos',
		'LaInteligenciaArtificialsurgeapartirdedesarrollosde:.': 'Diversas áreas (Matemáticas, Informática, Neurociencia, Psicología, Filosofía, Economía, etc...',
		'¿Porquémotivoseusanlosgrafosimplícitosalresolverunproblema?.': 'Porque los grafos explícitos son demasiado grandes como para mantenerlos en memoria.',
		'Lasheurísticassoncriterios,métodosoprincipiosparadecidircuáldeentrevariasaccionesprometeserlamejorparaalcanzarunameta..': 'verdadero',
		'EnelalgoritmoA*lafuncióngesunvalorquenocambiaalolargodelalgoritmo.': 'falso',
		'LaIAsurgeapartir:.': 'Todas las anteriores y muchas más.',
		'¿Mediantequéformaoformasdeinteracción,interactúanfundamentalmentelosagentesenlaRoboCup?:.': 'Cooperación   \nCoordinación',
		'¿puedeunagentereactivopeseaconocerelmediocometererrores?.': 'Si, su solución no tiene por qué ser la óptima',
		'Delossiguientesalgoritmos¿cuáltienemásposibilidadesdecaerenunmáximooenunmínimolocal?.': 'Escalada máxima pendiente',
		'¿Cuáldelossiguientestiposdeagenteutilizanunmodelosimbólicoexplícitodelmundo?:___________.': 'Agentes deliberativos',
		'ElmétododebúsquedaBacktrackingovueltaatrásseusapreferentementeen....': 'Sudoku.  \nJuego del Laberinto.  \nn-Damas.',
		'Enelalgoritmominimax,unjuegoseplanteacomounproblemade.': 'Maximización del beneficio del jugador propio',
		'LanotaciónMINMAXparacuantosjugadoressepuedeusar?.': '2   \nTodos los que sean necesarios',
		'Unmodelocognitivoseasociacon:.': 'Sistemas que piensan como humanos',
		'ElalgoritmoA*esuncasoparticulardelalgoritmodeDijkstra.': 'falso',
		'Cualdeentrelossiguientesalgoritmosdeescaladareducelaposibilidaddecaerenóptimoslocales..': 'enfriamiento simulado',
		'Enunsistemabasadoenelconocimiento,elmotordeinferencia.': 'permite razonar sobre el conocimiento de la base de conocimiento y los datos proporcionados por un usuario.'
};

//Obtenemos todos los elementos strong y los recorremos
var links = document.getElementsByTagName('strong');
for (var i = 0; i < links.length; i++) {
	//Buscamos la cabecera de la pregunta
	if (links[i].className == 'tituloGift') {
		//Agregamos la respuesta al title, así lo veremos como tooltip
		var question = links[i].textContent.replace(/ /g, '').trim();

		links[i].title = obj[question];
		try {
			var answers = obj[question].split('\n');

			for (var answer in answers) {

				var labels = links[i].parentNode.getElementsByTagName('input');

				for(var j = 0; j < labels.length; j++) {

					var itm = labels[j];

					if (itm.type == 'checkbox') {

						if (itm.nextSibling.textContent.trim() === answers[answer].trim()) {
							itm.checked = true;
						}
					} else if (itm.type == 'radio') {
						if (itm.value === 'Verdadero' && answers[answer] === 'verdadero') {
							itm.checked = true;
						} else if (itm.value === 'Falso' && answers[answer] === 'falso') {
							itm.checked = true;
						}
					}
				}
			}
			// Comprobamos si hay combos (esto es  fijo)
			var selects = links[i].parentNode.getElementsByTagName('select');
			if (selects.length > 0) {
				// Opcion combo 1
				var resp = answers[0].split(' -> ');
				var options = selects[0].getElementsByTagName('option');
				for (opt in options) {
					if (options[opt].value.trim() === resp[1].trim()) {
						options[opt].selected = true;
						break;
					}
				}
				// Opcion combo 2
				resp = answers[1].split(' -> ');
				options = selects[1].getElementsByTagName('option');
				for (opt in options) {
					if (options[opt].value.trim() === resp[1].trim()) {
						options[opt].selected = true;
						break;
					}
				}
				// Opcion combo 3
				resp = answers[2].split(' -> ');
				options = selects[2].getElementsByTagName('option');
				for (opt in options) {
					if (options[opt].value.trim() === resp[1].trim()) {
						options[opt].selected = true;
						break;
					}
				}
			}
		} catch(err) {
			console.log(err);
		}
	}
}
